# Generated by Django 4.0.4 on 2022-04-18 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='09[0-3][0-9]-?[0-9]{3}-?[0-9]{4}')])),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
