# Generated by Django 4.0.4 on 2022-04-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userregistermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistermodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
