# Generated by Django 4.0.4 on 2022-04-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
